### ISSUE TITLE
NFIRS Fire Incident Data.csv - Investigate Null Values

### ISSUE THREAD

**Issue by thwhitfield** [DataKind-DC/rcp2#27]
NFIRS Fire Incident Data.csv, which is the updated NFIRS fire dataset we're now using, has ~270,000 null values for Fire Station ID (FDID), when the previous version of the dataset didn't have any.

**Comment by kelsonSS** [comment]
I believe Jake also said there were a number of locations with GEOIDS of 000000001, which should probably be cleaned to be non-matches.

**Comment by jessezlotoff** [comment]
Thanks for flagging.  I'll take a look at this tonight.

**Comment by kelsonSS** [comment]
From the Discussion online today does that mean that this has been taken care of ?

**Comment by thwhitfield** [comment]
This is still in progress as of today.
