### ISSUE TITLE
Use SVI and HFC Data to identify factors related to fire alarm rate, fire rate, and lives saved rate

### ISSUE THREAD

**Issue by thwhitfield** [DataKind-DC/rcp2#29]
Data Sources: SVI, HFC Home Visits, HVC Lives Saved

- [ ] Use SVI and HFC data to identify common demographic and economic themes for Census Tract areas where alarms were installed. Document methodology and results

- [ ] Home Fire Area Profiles - Use SVI and HFC data to identify common demographic and economic themes for Census Tract areas reporting fires. Document methodology and results

- [ ] Lives Saved Area Profiles - Use SVI and HFC data to identify common themes for Lives Saved Locations. Document methodology and results

**Comment by Trav-work** [comment]
test

**Comment by pmallari** [comment]
Working on Lives Saved Area Profiles
