### ISSUE TITLE
Calculate rurality of counties, census tracts, and census block groups

### ISSUE THREAD

**Issue by thwhitfield** [DataKind-DC/rcp2#30]
Data sources: SVI, GIS, Census Data

- [x] County Rurality (Populated Areas) - Use SVI sq mile and population estimate data (E_TOTPOP) to determine rurality of populated areas in counties. Exclude any Census Tracts w/ 0 est pop. Score and rank order.

- [x] Census Tract Rurality (Populated Tracts) - Determine (and document) means to measure Census Tract Rurality (see Census Tract Rurality Tab). Exclude zero pop areas, score and rank order.

- [x] Census Block Group Rurality (Populated Block Groups) - Based on outputs from census tract rurality, determine means to assign rurality scores to block groups (based on size most likely). Should be relative to tract rurality score

**Comment by JakeJan** [comment]
This task is complete. Data was pulled from USDA which used Census data to include population density and commuting time/distance to determine rurality at the tract level. Working backwards one should be able to determine the rurality of counties and blockgroups (components of tract). If a tract is deemed to be rural one should assume that all corresponding blocks are also rural. Data resides in Master Data folder under "Census Tract Rurality"
