### ISSUE TITLE
Calculate absolute and driving distance from GEOIDs to closest one or more fire stations

### ISSUE THREAD

**Issue by thwhitfield** [DataKind-DC/rcp2#33]
Data Sources - FD Locations, GEOID geographies

- [ ] Assign GEOID (Full FIPS) to FD Locations File - Use FD Location file's Lat Longs to identify Census Block Group Info (GEOID) for all Fire Stations, update master file.

- [ ] Determine distance between FD and Tracts - Determine as the crow flies distance to nearest fire station from census tract centroid, Document distance in output. Denote if paid or volunteer, if located in same county, and FDID

- [ ] Determine distance between FD and Block Group - Determine as the crow flies distance to nearest fire station from census block group centroid, Document distance in output. Denote if paid or volunteer, if located in same county, and FDID

- [ ] Determine Avg Drive time from FD to Census Tract Boundary - Use FD location data to determine closest possible drive distance to ingress at census tract level. Denote if paid or volunteer, if located in same county, and FDID

- [ ] Determine Avg Drive time from FD to Census Block Group Boundary - Use FD location data to determine closest possible drive distance to ingress at census block group level. Denote if paid or volunteer, if located in same county, and FDID

**Comment by nbanion** [comment]
Outlining for this issue. Some details from @kelsonSS:

> I've got an old notebook that can efficiently calculate the haversine (spherical earth) distance and does so efficiently
>
> another thing that could be useful would be to have an adjacency table for census tracts. it would make the above task much faster computationally: https://gis.stackexchange.com/questions/281652/find-all-neighbors-using-geopandas
> 
> |Tract       |Neighbors                                    |
> |----------|------------------------------------|
> |01232...1|   01232...2, 01232...45, 01232...23|
> |01232...2|   ...                                                |
> |....           |   ...                                                |
> 
> shapefiles are in the google drive under 03_shapefiles. you'd need to combine the .shp files. Add the result to your master project data folder. Call the project CreateAdjacencyTableTracts and put it in code/FeatureEngineering

**Comment by kelsonSS** [comment]
Notebook I was talking about is also in featureEngineering. The File I/O will likely needed to be updated to use Pathlib and use the updated NFIRS File name

**Comment by nbanion** [comment]
Would you like me to add this functionality as a module in the `src` package?

I want to respect project conventions, and I don't know too much about your workflow yet. It looks like data processing often occurs in individual scripts and notebooks with instructions for coordinating them. In case you've wanted to build a package, I can plan for that.

Some possible advantages to packaging:

- We can reuse the same code in multiple notebooks.
- We can automate data processing steps in a Makefile or other scripts.
- We can potentially auto-document using Sphinx.
- Version control diffs may be easier to work with for `.py` than for `.ipynb`.

**Comment by kelsonSS** [comment]
as you have noted. We've currently just been rapidly iterating on the models to get to version 1.0. As we approach having a usable final product. Things like packaging, documentation, and automation are going to become more important. 

So I say go for it. It would be good to have an example to show to the team.

**Comment by nbanion** [comment]
The [osmnx](https://github.com/gboeing/osmnx) package looks promising for calculating driving distance. 

The package uses Open Street Maps street networks to-- among other things-- calculate [shortest distances and travel times](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/02-routing-speed-time.ipynb).

The package has also implemented [haversine distance calculations](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.great_circle_vec)-- though @kelsonSS has an elegant solution in the existing notebook.
