### ISSUE TITLE
ACS Data Exploration

### ISSUE THREAD

**Issue by kelsonSS** [DataKind-DC/rcp2#43]
We recently cleaned all of the ACS data at the block level. We need to do some exploratory data analysis to QC and look at some simple trends within this data. 
Data is located in: **Master Project Data**  > **ACS 5yr Block Data**

- [ ] Using missingno or pandas create a visualization for the number of Nan's / Missing  numbers in each column of the data 

- [ ]  Using seaborne (or your favorite plotting tool) create histograms of each column. Are the answers normally distributed? if no, can they be easily clustered ( ex low-income, medium-income, high-income)? 

- [ ] Using seaborne( or your favorite plotting tool) create a correlation matrix of the columns in the ACS data ( see thw_1.0_EDA_NFIRS_SVI in the notebooks page for inspiration). What columns are highly correlated with eachother? 
** note ** if the column isn't population adjusted (it isnt' a percentage or   <1) do that first or it will be correlated with block size.

**Comment by Jaboola9** [comment]
I'll take this on.
