### ISSUE TITLE
write script to download google drive directory

### ISSUE THREAD

**Issue by thwhitfield** [DataKind-DC/rcp2#61]
I think it would be helpful if we could write a script to download the raw and processed data files from google drive, and then place that into the makefile as the first step. I've been able to download individual files using [gdown](https://github.com/wkentaro/gdown), but I haven't been able to figure out how to download a whole google drive directory. 

If anyone knows of a package or has an approach to download a whole google drive directory as part of a script, that would be great.

**Comment by kelsonSS** [comment]
I would say for now write the makefiles assuming that the data is already in the correct folder on your computer. We haven't had any current users have any difficulty downloading the data thus-far.

So if there is an easy way to do it great, otherwise I think it's a low-priority item.

**Comment by nbanion** [comment]
The gdown package author suggests a [workaround](https://github.com/wkentaro/gdown/issues/9#issuecomment-325209445) with another tool of theirs.

In our case, we'll have a list of the files to download. The script could make the directory structure locally and then just populate it with the individual files. I recently added a `src/utils.py`, which might be a convenient place to inventory the file URLs.

**Comment by nbanion** [comment]
One caution: I recently tried this approach on another project, and something caused the UUIDs in the file URLs to change on Google Drive. Not sure if this had to do with editing or renaming the files in the cloud. Just a possible snag to look out for.

**Comment by nbanion** [comment]
I'm going to research [Pooch](https://github.com/fatiando/pooch) a bit. Sounds like it might be geared toward this problem. One intriguing feature: it selectively downloads files that are missing local copies or that need updating.
