### ISSUE TITLE
Import project documentation to Read the Docs.

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/rcp2#68]
Host our Sphinx documentation on [Read the Docs](https://readthedocs.org/) so that it is easy for users to access searchable, readable documentation about this project and its codebase.

I already imported the [rcp2 documentation](https://readthedocs.org/projects/red-cross-fire-risk-map-v2/) from DataKind-DC/rcp2. The docs currently fail to build due to an issue with `requirements.txt`. I expect we can fix the issue with a Read the Docs config file.

Some resources for completing this issue:

- [Importing Your Documentation](https://docs.readthedocs.io/en/stable/intro/import-guide.html)
- [Configuration File](https://docs.readthedocs.io/en/stable/config-file/index.html)
- [Build Process](https://docs.readthedocs.io/en/stable/builds.html)

**Comment by nbanion** [comment]
@kelsonSS , although I was able to import the docs from this public repo without having administrative rights to the repo, I can only edit the documentation and config files in the repo using the pull request workflow rather than pushing directly to DataKind-DC/rcp2. Usually that workflow is fine, but in this case it makes it difficult to iteratively troubleshoot errors in the Read the Docs build.

How would you like to proceed?

**Comment by jessezlotoff** [comment]
@nbanion, is it possible to import and build the docs from your forked repo?  Then you could update it iteratively and create the pull request to DataKind-DC/rcp2 once everything is working.

**Comment by nbanion** [comment]
I'm open to that solution. I suppose there would be a second version of the documentation out there linked to my repo, but that doesn't seem like a big problem.

**Comment by kelsonSS** [comment]
That seems like the best solution for now.

**Comment by nbanion** [comment]
Will do.
